package com.jangid.forging_process_management_service.entities.product;

public enum ItemStatus {
  PROCESSING_NOT_STARTED,
  FORGING_NOT_STARTED,
  FORGING_IN_PROGRESS,
  FORGING_COMPLETED,
  HEAT_TREATMENT_NOT_STARTED,
  HEAT_TREATMENT_IN_PROGRESS,
  HEAT_TREATMENT_PARTIALLY_COMPLETED,
  HEAT_TREATMENT_COMPLETED,
  MACHINING_NOT_STARTED,
  MACHINING_IN_PROGRESS,
  MACHINING_PARTIALLY_COMPLETED_WITHOUT_REWORK,
  MACHINING_PARTIALLY_COMPLETED_WITH_REWORK,
  MACHINING_COMPLETED,
  QUALITY_IN_PROGRESS,
  QUALITY_COMPLETED,
  ITEM_PROCESSING_FINISHED;
}
