package com.jangid.forging_process_management_service.entities.product;

public enum ItemStatus {
  PROCESSING_NOT_STARTED,//0
  FORGING_NOT_STARTED,//1
  FORGING_IN_PROGRESS,//2
  FORGING_COMPLETED,//3
  HEAT_TREATMENT_NOT_STARTED,//4
  HEAT_TREATMENT_IN_PROGRESS,//5
  HEAT_TREATMENT_PARTIALLY_COMPLETED,//6
  HEAT_TREATMENT_COMPLETED,//7
  MACHINING_NOT_STARTED,//8
  MACHINING_IN_PROGRESS,//9
  MACHINING_PARTIALLY_COMPLETED_WITHOUT_REWORK,//10
  MACHINING_PARTIALLY_COMPLETED_WITH_REWORK,//11
  MACHINING_COMPLETED,//12
  MACHINING_COMPLETED_WITH_REWORK,//13
  VENDOR_DISPATCH_COMPLETED,//14
  VENDOR_DISPATCH_RECEIVED,//15
  QUALITY_NOT_STARTED,//18
  QUALITY_FAILED_REWORK,//19
  QUALITY_IN_PROGRESS,//20
  QUALITY_COMPLETED,//21
  PARTIAL_DISPATCH_IN_PROGRESS,//22
  COMPLETE_DISPATCH_IN_PROGRESS,//23
  PARTIAL_DISPATCH_READY,//24
  COMPLETE_DISPATCH_READY,//25
  PARTIAL_DISPATCH_COMPLETED,//26
  COMPLETE_DISPATCH_COMPLETED,//27
  ITEM_PROCESSING_FINISHED,//28
  DISPATCH_DELETED_QUALITY;
}
