package com.jangid.forging_process_management_service.entities.product;

public enum ItemStatus {
  PROCESSING_NOT_STARTED,//0
  FORGING_NOT_STARTED,//1
  FORGING_IN_PROGRESS,//2
  FORGING_COMPLETED,//3
  HEAT_TREATMENT_NOT_STARTED,//4
  HEAT_TREATMENT_IN_PROGRESS,//5
  HEAT_TREATMENT_PARTIALLY_COMPLETED,//6
  HEAT_TREATMENT_COMPLETED,//7
  MACHINING_NOT_STARTED,//8
  MACHINING_IN_PROGRESS,//9
  MACHINING_PARTIALLY_COMPLETED_WITHOUT_REWORK,//10
  MACHINING_PARTIALLY_COMPLETED_WITH_REWORK,//11
  MACHINING_COMPLETED,//12
  MACHINING_COMPLETED_WITH_REWORK,//13
  QUALITY_IN_PROGRESS,//14
  QUALITY_COMPLETED,//15
  ITEM_PROCESSING_FINISHED;//16
}
