-- ===================================
-- Invoice Cancellation, E-Invoice Support, Manual Invoice Support, and Work Type
-- Version: V1_71
-- Description: Adds cancellation tracking fields, e-invoice compliance fields, manual invoice support, and work type to invoice table
-- Date: 2025-11-01 (Updated: 2025-11-02)
-- ===================================

-- ===================================
-- PART 1: Invoice Cancellation Fields
-- ===================================

-- Add cancellation tracking fields
ALTER TABLE invoice 
ADD COLUMN cancelled_by VARCHAR(100),
ADD COLUMN cancellation_reason VARCHAR(500),
ADD COLUMN cancellation_date TIMESTAMP;

-- Add index for cancellation queries
CREATE INDEX idx_invoice_cancellation_date ON invoice(cancellation_date);

-- Add comments for documentation
COMMENT ON COLUMN invoice.cancelled_by IS 'Name of person who cancelled the invoice';
COMMENT ON COLUMN invoice.cancellation_reason IS 'Reason for invoice cancellation';
COMMENT ON COLUMN invoice.cancellation_date IS 'Date and time when invoice was cancelled';


-- ===================================
-- PART 2: E-Invoice Fields
-- ===================================

-- Add E-Invoice fields for GST compliance
ALTER TABLE invoice ADD COLUMN irn VARCHAR(64);
COMMENT ON COLUMN invoice.irn IS 'Invoice Reference Number (IRN) - Generated by GST e-invoice portal';

ALTER TABLE invoice ADD COLUMN ack_no VARCHAR(50);
COMMENT ON COLUMN invoice.ack_no IS 'Acknowledgement Number from GST e-invoice portal';

ALTER TABLE invoice ADD COLUMN ack_date TIMESTAMP;
COMMENT ON COLUMN invoice.ack_date IS 'Acknowledgement Date from GST e-invoice portal';

ALTER TABLE invoice ADD COLUMN qr_code_data VARCHAR(1000);
COMMENT ON COLUMN invoice.qr_code_data IS 'QR Code data for e-invoice - Contains digitally signed invoice data';

-- Create index for IRN for faster lookups (as it may be used for validation)
CREATE INDEX idx_invoice_irn ON invoice(irn);

-- Create index for ack_date for reporting and compliance purposes
CREATE INDEX idx_invoice_ack_date ON invoice(ack_date);


-- ===================================
-- PART 3: Manual Invoice Support
-- ===================================

-- Add is_manual_invoice column to support invoices not associated with dispatch batches
ALTER TABLE invoice ADD COLUMN is_manual_invoice BOOLEAN DEFAULT FALSE;

-- Add comment
COMMENT ON COLUMN invoice.is_manual_invoice IS 'Indicates if invoice is manually created without dispatch batch association';

-- Create index for efficient querying of manual invoices
CREATE INDEX idx_invoice_manual ON invoice(is_manual_invoice, tenant_id) WHERE deleted = false;


-- ===================================
-- PART 4: Work Type Support for Invoice Numbering
-- ===================================

-- Add work_type column to store work type (WITH_MATERIAL or JOB_WORK_ONLY)
-- Purpose: Store work type in invoice for proper invoice numbering series selection
-- This allows invoices for non-order-based dispatch batches to have user-selected work types
ALTER TABLE invoice ADD COLUMN work_type VARCHAR(20);

-- Add comment for documentation
COMMENT ON COLUMN invoice.work_type IS 'Work type for invoice (WITH_MATERIAL or JOB_WORK_ONLY) - determines invoice numbering series and terms';

-- Create index for potential queries filtering by work_type
CREATE INDEX idx_invoice_work_type ON invoice(work_type);

-- Note: Existing invoices will have NULL work_type, which will be determined dynamically
-- during approval if needed (backward compatibility)

