-- Migration Script: Add E-Invoice support
-- Version: V1_79
-- Description: Creates tenant_einvoice_credentials table and adds E-Invoice fields to invoice table

BEGIN;

-- ==========================================
-- Part 1: Create tenant_einvoice_credentials table
-- ==========================================

-- Sequence for tenant_einvoice_credentials ID generation
CREATE SEQUENCE IF NOT EXISTS tenant_einvoice_credentials_sequence START 1 INCREMENT BY 1;

-- Tenant E-Invoice Credentials table
CREATE TABLE IF NOT EXISTS tenant_einvoice_credentials (
    id BIGINT PRIMARY KEY DEFAULT nextval('tenant_einvoice_credentials_sequence'),
    
    -- Relationships
    tenant_id BIGINT NOT NULL,
    gsp_config_id BIGINT NOT NULL,
    
    -- E-Invoice Credentials (tenant-specific)
    einv_gstin VARCHAR(15) NOT NULL,

    -- Auth Token Management
    auth_token VARCHAR(1000),
    sek VARCHAR(500),  -- Session Encryption Key
    token_expiry TIMESTAMP,
    
    -- Configuration
    einv_threshold DECIMAL(15,2) DEFAULT 5000000.00,  -- Default 5 crores (50 lakhs) as per GST regulations
    is_active BOOLEAN DEFAULT FALSE,
    
    -- Audit Fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT fk_tenant_einv_credentials_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id),
    CONSTRAINT fk_tenant_einv_credentials_gsp_config FOREIGN KEY (gsp_config_id) REFERENCES gsp_configuration(id),
    CONSTRAINT uq_tenant_einv_credentials_tenant UNIQUE (tenant_id)
);

-- Indexes for tenant_einvoice_credentials table
CREATE INDEX IF NOT EXISTS idx_tenant_einv_credentials_tenant ON tenant_einvoice_credentials(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_einv_credentials_gsp_config ON tenant_einvoice_credentials(gsp_config_id);
CREATE INDEX IF NOT EXISTS idx_tenant_einv_credentials_active ON tenant_einvoice_credentials(is_active) WHERE is_active = TRUE;

-- Comments for tenant_einvoice_credentials table
COMMENT ON TABLE tenant_einvoice_credentials IS 'Stores tenant-specific E-Invoice GSP credentials and configuration';
COMMENT ON COLUMN tenant_einvoice_credentials.einv_gstin IS 'E-Invoice GSTIN (tenant-specific)';
COMMENT ON COLUMN tenant_einvoice_credentials.auth_token IS 'Current authentication token from GSP API';
COMMENT ON COLUMN tenant_einvoice_credentials.sek IS 'Session Encryption Key from GSP API';
COMMENT ON COLUMN tenant_einvoice_credentials.token_expiry IS 'Authentication token expiry timestamp';
COMMENT ON COLUMN tenant_einvoice_credentials.einv_threshold IS 'Threshold value for mandatory E-Invoice (default 5 crores = 50,00,000 as per GST regulations)';
COMMENT ON COLUMN tenant_einvoice_credentials.is_active IS 'Whether this tenant configuration is active';

-- ==========================================
-- Part 2: Add E-Invoice fields to invoice table
-- ==========================================

-- Add E-Invoice generation date/time field
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS einvoice_date TIMESTAMP;
COMMENT ON COLUMN invoice.einvoice_date IS 'E-Invoice generation date/time (for display and tracking)';

-- Add E-Invoice alert message field
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS einvoice_alert_message VARCHAR(500);
COMMENT ON COLUMN invoice.einvoice_alert_message IS 'Alert message from E-Invoice GSP response';

-- Add E-Invoice details JSON field (for caching complete IRN details)
ALTER TABLE invoice ADD COLUMN IF NOT EXISTS einvoice_details_json TEXT;
COMMENT ON COLUMN invoice.einvoice_details_json IS 'Complete E-Invoice details JSON from Get IRN API - cached for future reference';

-- Create index for invoice IRN lookup
CREATE INDEX IF NOT EXISTS idx_invoice_irn ON invoice(irn) WHERE irn IS NOT NULL;

-- ==========================================
-- Part 3: Update existing comments (if needed)
-- ==========================================

-- Ensure IRN field has proper documentation
COMMENT ON COLUMN invoice.irn IS 'Invoice Reference Number (IRN) - 64 character unique identifier generated by GST portal for E-Invoice';

COMMIT;
