-- Migration Script: Add E-Way Bill GSP API fields to Delivery Challan table
-- Version: V1_80
-- Description: Adds E-Way Bill form fields and response fields for tracking E-Way Bill generation via GSP API

BEGIN;

-- Add E-Way Bill alert field
ALTER TABLE delivery_challan ADD COLUMN IF NOT EXISTS eway_bill_alert_message VARCHAR(500);

-- Add E-Way Bill details JSON field (stores complete GetEwayBill API response)
ALTER TABLE delivery_challan ADD COLUMN IF NOT EXISTS eway_bill_details_json TEXT;
COMMENT ON COLUMN delivery_challan.eway_bill_details_json IS 'Complete E-Way Bill details JSON from GetEwayBill API - cached for printing';

-- Add E-Way Bill form fields (captured during generation)
ALTER TABLE delivery_challan ADD COLUMN IF NOT EXISTS eway_bill_supply_type VARCHAR(1);
COMMENT ON COLUMN delivery_challan.eway_bill_supply_type IS 'Supply Type: O = Outward, I = Inward';

ALTER TABLE delivery_challan ADD COLUMN IF NOT EXISTS eway_bill_sub_supply_type INTEGER;
COMMENT ON COLUMN delivery_challan.eway_bill_sub_supply_type IS 'Sub Supply Type: 4=Job Work, 5=Own Use, 6=Job Work Returns, 7=Sales Return, 8=Others';

ALTER TABLE delivery_challan ADD COLUMN IF NOT EXISTS eway_bill_doc_type VARCHAR(3);
COMMENT ON COLUMN delivery_challan.eway_bill_doc_type IS 'Document Type: CHL = Challan, INV = Invoice, BIL = Bill of Supply';

ALTER TABLE delivery_challan ADD COLUMN IF NOT EXISTS eway_bill_transaction_type VARCHAR(1);
COMMENT ON COLUMN delivery_challan.eway_bill_transaction_type IS 'Transaction Type: 1 = Regular (Bill To = Ship To), 2 = Bill To-Ship To';

-- Update existing eway_bill_number column comment for consistency
COMMENT ON COLUMN delivery_challan.eway_bill_number IS 'E-Way Bill Number (12 digits) - Generated by GSP API or manually entered';
COMMENT ON COLUMN delivery_challan.eway_bill_alert_message IS 'Alert/notification message from GSP API during E-Way Bill generation';

COMMIT;
