BEGIN;

-- ==========================================
-- Rollback for V1_75__eway_bill_lightweight_implementation.sql
-- ==========================================
-- This script reverses the lightweight E-Way Bill implementation:
-- 1. Removes E-Way Bill fields from invoice and delivery_challan tables
-- 2. Recreates the old eway_bill table (if needed for data recovery)
-- 
-- WARNING: This will drop E-Way Bill data stored in invoice and delivery_challan tables.
-- Ensure you have a backup before running this rollback.
-- ==========================================

-- Part 1: Remove E-Way Bill fields from delivery_challan table
-- ==========================================

-- Drop index first
DROP INDEX IF EXISTS idx_challan_eway_bill_number;

-- Remove columns
ALTER TABLE delivery_challan
DROP COLUMN IF EXISTS eway_bill_number,
DROP COLUMN IF EXISTS eway_bill_date,
DROP COLUMN IF EXISTS eway_bill_valid_until;


-- Part 2: Remove E-Way Bill fields from invoice table
-- ==========================================

-- Drop index first
DROP INDEX IF EXISTS idx_invoice_eway_bill_number;

-- Remove columns
ALTER TABLE invoice
DROP COLUMN IF EXISTS eway_bill_number,
DROP COLUMN IF EXISTS eway_bill_date,
DROP COLUMN IF EXISTS eway_bill_valid_until;


-- Part 3: Recreate old eway_bill table (optional - for data recovery)
-- ==========================================
-- Uncomment the following section if you need to restore the old table structure

/*
-- Sequence for eway_bill ID generation
CREATE SEQUENCE eway_bill_sequence START 1 INCREMENT BY 1;

-- E-Way Bill table
CREATE TABLE eway_bill (
    id BIGINT PRIMARY KEY DEFAULT nextval('eway_bill_sequence'),
    eway_bill_number VARCHAR(20) UNIQUE,
    eway_bill_date TIMESTAMP NOT NULL,
    
    -- Relationships
    dispatch_batch_id BIGINT,
    invoice_id BIGINT,
    delivery_challan_id BIGINT,
    
    -- Document Details
    document_number VARCHAR(50) NOT NULL,
    document_date TIMESTAMP NOT NULL,
    document_type VARCHAR(20) NOT NULL,
    
    -- Supplier Details
    supplier_gstin VARCHAR(15) NOT NULL,
    supplier_name VARCHAR(200) NOT NULL,
    supplier_state_code VARCHAR(2) NOT NULL,
    supplier_pincode VARCHAR(6) NOT NULL,
    
    -- Recipient Details
    recipient_gstin VARCHAR(15),
    recipient_name VARCHAR(200) NOT NULL,
    recipient_state_code VARCHAR(2) NOT NULL,
    recipient_pincode VARCHAR(6) NOT NULL,
    
    -- Goods Details
    hsn_code VARCHAR(10),
    goods_description TEXT,
    total_quantity DECIMAL(15,3) DEFAULT 0,
    total_value DECIMAL(15,2) NOT NULL,
    
    -- Transportation Details
    transportation_mode VARCHAR(20) DEFAULT 'ROAD',
    transportation_distance INTEGER,
    vehicle_number VARCHAR(20),
    transporter_name VARCHAR(200),
    
    -- Validity and Status
    valid_from TIMESTAMP NOT NULL,
    valid_until TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    
    -- Standard Audit Fields
    tenant_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE,
    
    -- Foreign Keys
    CONSTRAINT fk_eway_bill_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id),
    CONSTRAINT fk_eway_bill_dispatch_batch FOREIGN KEY (dispatch_batch_id) REFERENCES dispatch_batch(id),
    CONSTRAINT fk_eway_bill_invoice FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    CONSTRAINT fk_eway_bill_challan FOREIGN KEY (delivery_challan_id) REFERENCES delivery_challan(id),
    
    -- Constraints
    CONSTRAINT chk_eway_bill_document_type CHECK (document_type IN ('INVOICE', 'CHALLAN')),
    CONSTRAINT chk_eway_bill_status CHECK (status IN ('ACTIVE', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT chk_eway_bill_transportation_mode CHECK (transportation_mode IN ('ROAD', 'RAIL', 'AIR', 'SHIP', 'OTHER'))
);

ALTER TABLE delivery_challan
ADD COLUMN IF NOT EXISTS eway_bill_number VARCHAR(50);

-- Indexes for eway_bill table
CREATE INDEX idx_eway_bill_dispatch_batch ON eway_bill(dispatch_batch_id);
CREATE INDEX idx_eway_bill_invoice ON eway_bill(invoice_id);
CREATE INDEX idx_eway_bill_challan ON eway_bill(delivery_challan_id);
CREATE INDEX idx_eway_bill_tenant_status ON eway_bill(tenant_id, status);
CREATE INDEX idx_eway_bill_validity ON eway_bill(valid_until);
CREATE INDEX idx_eway_bill_deleted ON eway_bill(deleted);
CREATE INDEX idx_eway_bill_number ON eway_bill(eway_bill_number) WHERE eway_bill_number IS NOT NULL;
CREATE INDEX idx_eway_bill_date ON eway_bill(eway_bill_date);

-- Comments for eway_bill table
COMMENT ON TABLE eway_bill IS 'Stores E-Way Bill information for dispatch tracking and GST compliance';
COMMENT ON COLUMN eway_bill.eway_bill_number IS 'Unique E-Way Bill number generated by GST portal';
COMMENT ON COLUMN eway_bill.eway_bill_date IS 'Date when E-Way Bill was generated';
COMMENT ON COLUMN eway_bill.document_type IS 'Type of document - INVOICE or CHALLAN';
COMMENT ON COLUMN eway_bill.transportation_mode IS 'Mode of transportation - ROAD, RAIL, AIR, SHIP, OTHER';
COMMENT ON COLUMN eway_bill.transportation_distance IS 'Transportation distance in kilometers';
COMMENT ON COLUMN eway_bill.valid_from IS 'E-Way Bill validity start date';
COMMENT ON COLUMN eway_bill.valid_until IS 'E-Way Bill validity end date';
COMMENT ON COLUMN eway_bill.status IS 'Current status - ACTIVE, CANCELLED, or EXPIRED';
*/

COMMIT;
